import type { GetEntityResponse } from '@shared/api/entity';

export const someEntityData: GetEntityResponse = [
  {
    title: 'Название',
    description: 'Описание',
    city: 'Город',
    phone: 'Телефон',
    email: 'e-mail',
    website: 'Сайт',
    username: 'Логин',
    firstName: 'Имя',
  },
  {
    id: 0,
    title: 'Sed do eiusmod tempor',
    description: 'Non proident sunt',
    city: 'Сочи',
    phone: '8-284-513-76-41',
    email: 'qwerty123@test.ru',
    website: 'qwerty123.ru',
    username: 'qazwsxedc',
    firstName: 'Jack',
  },
  {
    id: 1,
    title: 'Incididunt ut labore',
    description: 'Excepteur sint occaecat',
    city: 'Санкт-Петербург',
    phone: '8-702-895-92-43',
    email: 'qwerty@test.ru',
    website: 'qwerty.ru',
    username: 'qwe123',
    firstName: 'Ryan',
  },
  {
    id: 2,
    title: 'Non proident sunt',
    description: 'Excepteur sint occaecat',
    city: 'Москва',
    phone: '8-254-879-78-35',
    email: 'qwerty@test.ru',
    website: 'qwerty123.ru',
    username: 'user',
    firstName: 'Walker',
  },
  {
    id: 3,
    title: 'Excepteur sint occaecat',
    description: 'Incididunt ut labore',
    city: 'Сочи',
    phone: '8-834-324-94-01',
    email: 'something@test.ru',
    website: 'qwerty.ru',
    username: 'user',
    firstName: 'Walker',
  },
  {
    id: 4,
    title: 'Excepteur sint occaecat',
    description: 'Non proident sunt',
    city: 'Москва',
    phone: '8-625-052-21-87',
    email: 'test@test.ru',
    website: 'qwerty.ru',
    username: 'qazwsxedc',
    firstName: 'Walker',
  },
  {
    id: 5,
    title: 'Non proident sunt',
    description: 'Non proident sunt',
    city: 'Екатеринбург',
    phone: '8-158-994-90-78',
    email: 'something@test.ru',
    website: 'qwerty.ru',
    username: 'user',
    firstName: 'Ryan',
  },
  {
    id: 6,
    title: 'Incididunt ut labore',
    description: 'Ut enim ad minim veniam',
    city: 'Екатеринбург',
    phone: '8-593-293-62-09',
    email: 'test@test.ru',
    website: 'test.ru',
    username: 'qazwsxedc',
    firstName: 'Jack',
  },
  {
    id: 7,
    title: 'Excepteur sint occaecat',
    description: 'Ut enim ad minim veniam',
    city: 'Санкт-Петербург',
    phone: '8-686-040-15-25',
    email: 'qwerty@test.ru',
    website: 'something.ru',
    username: 'qweqwe',
    firstName: 'Sienna',
  },
  {
    id: 8,
    title: 'Incididunt ut labore',
    description: 'Sed do eiusmod tempor',
    city: 'Екатеринбург',
    phone: '8-053-967-73-68',
    email: 'something@test.ru',
    website: 'qwerty.ru',
    username: 'qazwsxedc',
    firstName: 'Sienna',
  },
  {
    id: 9,
    title: 'Excepteur sint occaecat',
    description: 'Ut enim ad minim veniam',
    city: 'Санкт-Петербург',
    phone: '8-796-132-52-94',
    email: 'test@test.ru',
    website: 'test.ru',
    username: 'qazwsxedc',
    firstName: 'Jack',
  },
  {
    id: 10,
    title: 'Sed do eiusmod tempor',
    description: 'Incididunt ut labore',
    city: 'Санкт-Петербург',
    phone: '8-707-128-53-44',
    email: 'qwerty@test.ru',
    website: 'qwerty123.ru',
    username: 'qazwsxedc',
    firstName: 'Jack',
  },
  {
    id: 11,
    title: 'Excepteur sint occaecat',
    description: 'Sed do eiusmod tempor',
    city: 'Сочи',
    phone: '8-048-618-50-89',
    email: 'something@test.ru',
    website: 'test.ru',
    username: 'qweqwe',
    firstName: 'Jack',
  },
  {
    id: 12,
    title: 'Non proident sunt',
    description: 'Sed do eiusmod tempor',
    city: 'Сочи',
    phone: '8-123-274-64-60',
    email: 'test@test.ru',
    website: 'qwerty.ru',
    username: 'qazwsxedc',
    firstName: 'Jack',
  },
  {
    id: 13,
    title: 'Sed do eiusmod tempor',
    description: 'Sed do eiusmod tempor',
    city: 'Москва',
    phone: '8-775-883-47-87',
    email: 'something@test.ru',
    website: 'test.ru',
    username: 'qweqwe',
    firstName: 'Jack',
  },
  {
    id: 14,
    title: 'Ut enim ad minim veniam',
    description: 'Excepteur sint occaecat',
    city: 'Калининград',
    phone: '8-746-448-73-70',
    email: 'something@test.ru',
    website: 'qwerty.ru',
    username: 'qazwsxedc',
    firstName: 'Ryan',
  },
  {
    id: 15,
    title: 'Sed do eiusmod tempor',
    description: 'Excepteur sint occaecat',
    city: 'Москва',
    phone: '8-673-935-46-27',
    email: 'test@test.ru',
    website: 'something.ru',
    username: 'qazwsxedc',
    firstName: 'Walker',
  },
  {
    id: 16,
    title: 'Excepteur sint occaecat',
    description: 'Incididunt ut labore',
    city: 'Сочи',
    phone: '8-237-997-42-82',
    email: 'qwerty@test.ru',
    website: 'test.ru',
    username: 'qweqwe',
    firstName: 'Walker',
  },
  {
    id: 17,
    title: 'Incididunt ut labore',
    description: 'Excepteur sint occaecat',
    city: 'Москва',
    phone: '8-513-515-38-26',
    email: 'test@test.ru',
    website: 'qwerty123.ru',
    username: 'qwe123',
    firstName: 'Ryan',
  },
  {
    id: 18,
    title: 'Non proident sunt',
    description: 'Excepteur sint occaecat',
    city: 'Москва',
    phone: '8-686-523-92-13',
    email: 'test@test.ru',
    website: 'something.ru',
    username: 'user',
    firstName: 'Jack',
  },
  {
    id: 19,
    title: 'Incididunt ut labore',
    description: 'Non proident sunt',
    city: 'Сочи',
    phone: '8-133-773-95-91',
    email: 'something@test.ru',
    website: 'something.ru',
    username: 'user',
    firstName: 'Sienna',
  },
  {
    id: 20,
    title: 'Sed do eiusmod tempor',
    description: 'Sed do eiusmod tempor',
    city: 'Сочи',
    phone: '8-301-152-93-47',
    email: 'something@test.ru',
    website: 'test.ru',
    username: 'user',
    firstName: 'Jack',
  },
  {
    id: 21,
    title: 'Non proident sunt',
    description: 'Excepteur sint occaecat',
    city: 'Екатеринбург',
    phone: '8-184-699-28-36',
    email: 'qwerty123@test.ru',
    website: 'test.ru',
    username: 'qazwsxedc',
    firstName: 'Caroline',
  },
  {
    id: 22,
    title: 'Non proident sunt',
    description: 'Ut enim ad minim veniam',
    city: 'Екатеринбург',
    phone: '8-601-690-91-93',
    email: 'test@test.ru',
    website: 'something.ru',
    username: 'qweqwe',
    firstName: 'Walker',
  },
  {
    id: 23,
    title: 'Sed do eiusmod tempor',
    description: 'Non proident sunt',
    city: 'Екатеринбург',
    phone: '8-755-406-37-72',
    email: 'test@test.ru',
    website: 'test.ru',
    username: 'qweqwe',
    firstName: 'Walker',
  },
  {
    id: 24,
    title: 'Non proident sunt',
    description: 'Sed do eiusmod tempor',
    city: 'Москва',
    phone: '8-584-775-55-52',
    email: 'qwerty123@test.ru',
    website: 'qwerty.ru',
    username: 'qweqwe',
    firstName: 'Caroline',
  },
  {
    id: 25,
    title: 'Incididunt ut labore',
    description: 'Ut enim ad minim veniam',
    city: 'Москва',
    phone: '8-468-767-23-42',
    email: 'something@test.ru',
    website: 'qwerty123.ru',
    username: 'qweqwe',
    firstName: 'Sienna',
  },
  {
    id: 26,
    title: 'Sed do eiusmod tempor',
    description: 'Excepteur sint occaecat',
    city: 'Москва',
    phone: '8-413-805-11-56',
    email: 'qwerty123@test.ru',
    website: 'something.ru',
    username: 'qwe123',
    firstName: 'Jack',
  },
  {
    id: 27,
    title: 'Sed do eiusmod tempor',
    description: 'Sed do eiusmod tempor',
    city: 'Сочи',
    phone: '8-873-093-15-04',
    email: 'qwerty123@test.ru',
    website: 'something.ru',
    username: 'qweqwe',
    firstName: 'Jack',
  },
  {
    id: 28,
    title: 'Incididunt ut labore',
    description: 'Non proident sunt',
    city: 'Сочи',
    phone: '8-858-701-94-52',
    email: 'something@test.ru',
    website: 'qwerty.ru',
    username: 'qweqwe',
    firstName: 'Ryan',
  },
  {
    id: 29,
    title: 'Incididunt ut labore',
    description: 'Non proident sunt',
    city: 'Калининград',
    phone: '8-368-909-99-00',
    email: 'qwerty@test.ru',
    website: 'test.ru',
    username: 'qazwsxedc',
    firstName: 'Caroline',
  },
  {
    id: 30,
    title: 'Ut enim ad minim veniam',
    description: 'Sed do eiusmod tempor',
    city: 'Санкт-Петербург',
    phone: '8-037-888-85-90',
    email: 'test@test.ru',
    website: 'qwerty.ru',
    username: 'user',
    firstName: 'Ryan',
  },
  {
    id: 31,
    title: 'Incididunt ut labore',
    description: 'Non proident sunt',
    city: 'Екатеринбург',
    phone: '8-600-512-36-78',
    email: 'test@test.ru',
    website: 'qwerty123.ru',
    username: 'qwe123',
    firstName: 'Sienna',
  },
  {
    id: 32,
    title: 'Ut enim ad minim veniam',
    description: 'Ut enim ad minim veniam',
    city: 'Санкт-Петербург',
    phone: '8-201-286-11-37',
    email: 'qwerty123@test.ru',
    website: 'test.ru',
    username: 'user',
    firstName: 'Jack',
  },
  {
    id: 33,
    title: 'Incididunt ut labore',
    description: 'Non proident sunt',
    city: 'Екатеринбург',
    phone: '8-958-319-47-54',
    email: 'something@test.ru',
    website: 'test.ru',
    username: 'qwe123',
    firstName: 'Caroline',
  },
  {
    id: 34,
    title: 'Non proident sunt',
    description: 'Excepteur sint occaecat',
    city: 'Сочи',
    phone: '8-765-570-02-60',
    email: 'test@test.ru',
    website: 'something.ru',
    username: 'qazwsxedc',
    firstName: 'Ryan',
  },
  {
    id: 35,
    title: 'Excepteur sint occaecat',
    description: 'Non proident sunt',
    city: 'Калининград',
    phone: '8-067-763-21-98',
    email: 'test@test.ru',
    website: 'qwerty.ru',
    username: 'qwe123',
    firstName: 'Sienna',
  },
  {
    id: 36,
    title: 'Ut enim ad minim veniam',
    description: 'Excepteur sint occaecat',
    city: 'Москва',
    phone: '8-063-833-55-77',
    email: 'qwerty@test.ru',
    website: 'test.ru',
    username: 'qazwsxedc',
    firstName: 'Sienna',
  },
  {
    id: 37,
    title: 'Non proident sunt',
    description: 'Excepteur sint occaecat',
    city: 'Москва',
    phone: '8-874-720-97-30',
    email: 'qwerty@test.ru',
    website: 'test.ru',
    username: 'qwe123',
    firstName: 'Caroline',
  },
  {
    id: 38,
    title: 'Non proident sunt',
    description: 'Incididunt ut labore',
    city: 'Сочи',
    phone: '8-654-597-51-08',
    email: 'qwerty@test.ru',
    website: 'something.ru',
    username: 'qazwsxedc',
    firstName: 'Caroline',
  },
  {
    id: 39,
    title: 'Non proident sunt',
    description: 'Non proident sunt',
    city: 'Екатеринбург',
    phone: '8-608-441-91-37',
    email: 'test@test.ru',
    website: 'qwerty123.ru',
    username: 'qweqwe',
    firstName: 'Caroline',
  },
  {
    id: 40,
    title: 'Ut enim ad minim veniam',
    description: 'Excepteur sint occaecat',
    city: 'Санкт-Петербург',
    phone: '8-863-875-22-00',
    email: 'qwerty@test.ru',
    website: 'something.ru',
    username: 'qweqwe',
    firstName: 'Walker',
  },
  {
    id: 41,
    title: 'Non proident sunt',
    description: 'Non proident sunt',
    city: 'Калининград',
    phone: '8-948-679-97-02',
    email: 'test@test.ru',
    website: 'something.ru',
    username: 'user',
    firstName: 'Jack',
  },
  {
    id: 42,
    title: 'Excepteur sint occaecat',
    description: 'Excepteur sint occaecat',
    city: 'Екатеринбург',
    phone: '8-241-536-07-76',
    email: 'something@test.ru',
    website: 'qwerty123.ru',
    username: 'qwe123',
    firstName: 'Walker',
  },
  {
    id: 43,
    title: 'Excepteur sint occaecat',
    description: 'Ut enim ad minim veniam',
    city: 'Калининград',
    phone: '8-282-108-56-29',
    email: 'qwerty123@test.ru',
    website: 'qwerty123.ru',
    username: 'user',
    firstName: 'Ryan',
  },
  {
    id: 44,
    title: 'Excepteur sint occaecat',
    description: 'Incididunt ut labore',
    city: 'Сочи',
    phone: '8-497-723-99-20',
    email: 'qwerty@test.ru',
    website: 'qwerty123.ru',
    username: 'user',
    firstName: 'Jack',
  },
  {
    id: 45,
    title: 'Sed do eiusmod tempor',
    description: 'Sed do eiusmod tempor',
    city: 'Санкт-Петербург',
    phone: '8-220-330-22-26',
    email: 'test@test.ru',
    website: 'test.ru',
    username: 'qazwsxedc',
    firstName: 'Walker',
  },
  {
    id: 46,
    title: 'Incididunt ut labore',
    description: 'Incididunt ut labore',
    city: 'Екатеринбург',
    phone: '8-837-013-65-50',
    email: 'qwerty@test.ru',
    website: 'qwerty123.ru',
    username: 'qweqwe',
    firstName: 'Walker',
  },
  {
    id: 47,
    title: 'Incididunt ut labore',
    description: 'Non proident sunt',
    city: 'Санкт-Петербург',
    phone: '8-236-974-53-34',
    email: 'something@test.ru',
    website: 'qwerty123.ru',
    username: 'user',
    firstName: 'Walker',
  },
  {
    id: 48,
    title: 'Incididunt ut labore',
    description: 'Non proident sunt',
    city: 'Москва',
    phone: '8-108-373-88-73',
    email: 'something@test.ru',
    website: 'something.ru',
    username: 'qazwsxedc',
    firstName: 'Ryan',
  },
  {
    id: 49,
    title: 'Sed do eiusmod tempor',
    description: 'Ut enim ad minim veniam',
    city: 'Москва',
    phone: '8-604-429-35-26',
    email: 'test@test.ru',
    website: 'qwerty.ru',
    username: 'user',
    firstName: 'Caroline',
  },
];

export const createdSomeEntityItem = {
  id: 50,
  title: 'Some new Entity',
  description: 'Some new Entity description',
  city: 'Москва',
  phone: '8-123-456-78-91',
  email: 'some-new-entity@test.ru',
  website: 'some-new-entity.ru',
  username: 'some-new-entity',
  firstName: 'Name',
};
